export const breadcrumbLabels: Record<string, string> = {
  audit: "Auditoría",
  configure: "Configurar",
  "consent-documents": "Consentimientos del cliente",
  "app-content": "Contenido de la app",
  exports: "Exportaciones",
  files: "Archivos",
  expedienteId: "Expediente",
  cliente: "Cliente",
  metadata: "Metadata",
  exportId: "Exportación",
  jobId: "Job",
  jobs: "Jobs",
  "business-metadata": "Metadata de negocio",
  catalogs: "Catálogos",
  catalogCode: "Catálogo",
  "catalog-sync": "Sincronización de catálogo",
  current: "Actual",
  "data-catalog": "Catálogo de datos",
  "data-quality": "Calidad de datos",
  definitions: "Definiciones del motor",
  domains: "Dominios y glosario",
  // Sin esta entrada la miga de pan escribía el segmento crudo de la ruta: «events».
  events: "Eventos de dominio",
  "partner-contracts": "Contrato de comercios",
  endpoints: "Endpoints",
  governance: "Gobierno de datos",
  "privacy-requests": "Solicitudes de privacidad",
  glossary: "Glosario",
  guia: "Guía",
  official: "Oficial",
  impact: "Impacto",
  nodes: "Nodos",
  nodeId: "Nodo",
  policyId: "Política",
  termId: "Término",
  health: "Salud",
  issues: "Issues de calidad",
  lab: "Laboratorio",
  lineage: "Lineage",
  "my-notifications": "Mis notificaciones",
  "merchant-users": "Usuarios de comercio",
  operations: "Operaciones",
  partners: "Expedientes de comercio",
  portfolio: "Calificación de cartera",
  loans: "Préstamos",
  "work-queue": "Cola de trabajo",
  "manual-review-cases": "Revisión manual",
  "fraud-cases": "Casos de fraude",
  credit: "Crédito",
  products: "Productos",
  applications: "Solicitudes",
  "from-case": "Desde la cola",
  "pending-contacts": "Contactos sin verificar",
  "payment-claims": "Avisos de pago",
  support: "Soporte",
  cases: "Casos",
  caseId: "Caso",
  agents: "Agentes",
  customers: "Clientes",
  customerId: "Cliente",
  "investigation-summary": "Investigación",
  pii: "PII",
  permissions: "Permisos",
  policies: "Políticas",
  procesos: "Procesos",
  instancias: "Casos en curso",
  profile: "Perfil",
  qa: "QA",
  readiness: "Readiness Release",
  reportId: "Reporte",
  reports: "Reportes",
  request: "Request",
  "release-readiness": "Readiness Release",
  "review-queue": "Cola de revisión",
  roles: "Roles",
  runs: "Ejecuciones",
  search: "Búsqueda",
  security: "Seguridad",
  settings: "Configuración",
  session: "Sesión",
  sessions: "Sesiones",
  sessionId: "Sesión",
  stress: "Carga",
  suites: "Suites",
  systems: "Sistemas",
  table: "Tabla",
  tables: "Tablas",
  tools: "Herramientas",
  users: "Usuarios",
  ruleId: "Regla",
  rules: "Reglas",
  "risk-policy": "Política de riesgo",
  "ruleset-versions": "Versiones de ruleset",
  new: "Nueva",
  package: "Paquete",
  "risk-assessments": "Evaluaciones de riesgo",
  riskAssessmentRunId: "Evaluación",
  schema: "Esquema",
  versions: "Versiones",
  versionId: "Versión",
  tableId: "Tabla",
  "change-log": "Change log",
  "external-providers": "Proveedores externos",
  requests: "Solicitudes",
  audits: "Auditorías",
  notifications: "Mensajería interna",
  campaigns: "Campañas",
  "notification-policies": "Políticas de notificación",
  "decision-engine": "Motor de decisión",
  "decision-artifacts": "Motor de decisiones",
  artifacts: "Artefactos",
  "network-health": "Salud de la red",
  dashboard: "Panel de control",
  internal: "Inicio",
  login: "Acceso",
  "data-catalog-tables": "Tablas",
  entityId: "Entidad",
  internalUserId: "Usuario",
  runId: "Ejecución",
  suiteId: "Suite",
  profileId: "Perfil de carga",
  requestId: "Request",
  schemaName: "Esquema",
  tableName: "Tabla",
  providerCode: "Proveedor",
};
